# Generated by Django 3.2.6 on 2021-08-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text='chat_id', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(help_text='courseNum', max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courseQuery.user')),
            ],
        ),
    ]
